name: Use the same job name
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Do something
    uses: jessemyers/actions-test/.github/workflows/shared.yml@main

  also:
    name: Do something
    runs-on: ubuntu-latest
    steps:
      - name: no-op
        run: exit 0
